<?php
/**
 * Books PDF Export
 * Generates comprehensive PDF report of all books in library
 */

session_start();
require_once '../includes/db_connect.php';

// Check if admin is logged in
if (!isset($_SESSION['admin_id']) && !isset($_SESSION['AdminID'])) {
    die('Unauthorized access');
}

// Fetch all books with holding information
$sql = "
    SELECT 
        b.*,
        COUNT(h.HoldID) as TotalCopies,
        SUM(CASE WHEN h.Status = 'Available' THEN 1 ELSE 0 END) as AvailableCopies,
        SUM(CASE WHEN h.Status = 'Issued' THEN 1 ELSE 0 END) as IssuedCopies,
        GROUP_CONCAT(DISTINCT h.AccNo ORDER BY h.AccNo SEPARATOR ', ') as AccessionNumbers
    FROM Books b
    LEFT JOIN Holding h ON b.CatNo = h.CatNo
    GROUP BY b.CatNo
    ORDER BY b.Title
";

$stmt = $pdo->prepare($sql);
$stmt->execute();
$books = $stmt->fetchAll(PDO::FETCH_ASSOC);

// Set headers for PDF download
header('Content-Type: application/pdf');
header('Content-Disposition: attachment; filename="library_books_catalog_' . date('Y-m-d') . '.pdf"');

// Generate PDF using basic HTML to PDF conversion
// For better PDF generation, you can integrate TCPDF or FPDF library

// Simple HTML template that browsers can print to PDF
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Library Books Catalog</title>
    <style>
        @page {
            size: A4;
            margin: 20mm;
        }
        
        body {
            font-family: 'DejaVu Sans', Arial, sans-serif;
            font-size: 10pt;
            line-height: 1.4;
            color: #333;
        }
        
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 3px solid #263c79;
            padding-bottom: 15px;
        }
        
        .header h1 {
            color: #263c79;
            margin: 0 0 5px 0;
            font-size: 24pt;
        }
        
        .header h2 {
            color: #cfac69;
            margin: 0;
            font-size: 14pt;
            font-weight: normal;
        }
        
        .meta-info {
            text-align: right;
            margin-bottom: 20px;
            font-size: 9pt;
            color: #666;
        }
        
        .summary-stats {
            background: #f8f9fa;
            border: 2px solid #263c79;
            border-radius: 5px;
            padding: 15px;
            margin-bottom: 25px;
            display: table;
            width: 100%;
        }
        
        .summary-stats .stat {
            display: inline-block;
            margin-right: 30px;
        }
        
        .summary-stats .stat-label {
            font-weight: bold;
            color: #263c79;
        }
        
        .summary-stats .stat-value {
            color: #cfac69;
            font-size: 14pt;
            font-weight: bold;
        }
        
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
            page-break-inside: avoid;
        }
        
        thead {
            background: #263c79;
            color: white;
        }
        
        th {
            padding: 8px 5px;
            text-align: left;
            font-size: 9pt;
            font-weight: bold;
            border: 1px solid #1a2a5a;
        }
        
        td {
            padding: 6px 5px;
            border: 1px solid #ddd;
            font-size: 9pt;
            vertical-align: top;
        }
        
        tr:nth-child(even) {
            background-color: #f8f9fa;
        }
        
        tr:hover {
            background-color: #e9ecef;
        }
        
        .book-row {
            page-break-inside: avoid;
        }
        
        .book-title {
            font-weight: bold;
            color: #263c79;
        }
        
        .availability-good {
            color: #28a745;
            font-weight: bold;
        }
        
        .availability-warning {
            color: #ffc107;
            font-weight: bold;
        }
        
        .availability-danger {
            color: #dc3545;
            font-weight: bold;
        }
        
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 8pt;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
        
        @media print {
            .page-break {
                page-break-after: always;
            }
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>📚 WIET Library</h1>
        <h2>Books Catalog - Complete Collection</h2>
    </div>
    
    <div class="meta-info">
        <strong>Report Generated:</strong> <?php echo date('d F Y, H:i:s'); ?><br>
        <strong>Generated by:</strong> <?php echo $_SESSION['admin_name'] ?? 'Admin'; ?>
    </div>
    
    <div class="summary-stats">
        <div class="stat">
            <span class="stat-label">Total Books:</span>
            <span class="stat-value"><?php echo count($books); ?></span>
        </div>
        <div class="stat">
            <span class="stat-label">Total Copies:</span>
            <span class="stat-value"><?php 
                $totalCopies = array_sum(array_column($books, 'TotalCopies'));
                echo $totalCopies;
            ?></span>
        </div>
        <div class="stat">
            <span class="stat-label">Available:</span>
            <span class="stat-value"><?php 
                $availableCopies = array_sum(array_column($books, 'AvailableCopies'));
                echo $availableCopies;
            ?></span>
        </div>
        <div class="stat">
            <span class="stat-label">Issued:</span>
            <span class="stat-value"><?php 
                $issuedCopies = array_sum(array_column($books, 'IssuedCopies'));
                echo $issuedCopies;
            ?></span>
        </div>
    </div>
    
    <table>
        <thead>
            <tr>
                <th style="width: 7%;">Cat No.</th>
                <th style="width: 28%;">Title & Author</th>
                <th style="width: 15%;">Publisher & Year</th>
                <th style="width: 12%;">ISBN</th>
                <th style="width: 12%;">Subject</th>
                <th style="width: 8%;">Edition</th>
                <th style="width: 10%;">Copies</th>
                <th style="width: 8%;">Status</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($books as $book): 
                $availability = 0;
                if ($book['TotalCopies'] > 0) {
                    $availability = ($book['AvailableCopies'] / $book['TotalCopies']) * 100;
                }
                
                if ($availability >= 70) {
                    $statusClass = 'availability-good';
                    $statusText = '✓ Good';
                } elseif ($availability >= 40) {
                    $statusClass = 'availability-warning';
                    $statusText = '⚠ Low';
                } else {
                    $statusClass = 'availability-danger';
                    $statusText = '✗ Critical';
                }
            ?>
            <tr class="book-row">
                <td><?php echo htmlspecialchars($book['CatNo']); ?></td>
                <td>
                    <div class="book-title"><?php echo htmlspecialchars($book['Title']); ?></div>
                    <?php if (!empty($book['SubTitle'])): ?>
                        <small style="color: #666;"><?php echo htmlspecialchars($book['SubTitle']); ?></small><br>
                    <?php endif; ?>
                    <small style="color: #555;">
                        <?php 
                        $authors = array_filter([
                            $book['Author1'] ?? '',
                            $book['Author2'] ?? '',
                            $book['Author3'] ?? ''
                        ]);
                        echo htmlspecialchars(implode(', ', $authors));
                        ?>
                    </small>
                </td>
                <td>
                    <?php echo htmlspecialchars($book['Publisher'] ?? 'N/A'); ?><br>
                    <small style="color: #666;">
                        <?php echo htmlspecialchars($book['Year'] ?? 'N/A'); ?>
                        <?php if (!empty($book['Place'])): ?>
                            - <?php echo htmlspecialchars($book['Place']); ?>
                        <?php endif; ?>
                    </small>
                </td>
                <td><small><?php echo htmlspecialchars($book['ISBN'] ?? 'N/A'); ?></small></td>
                <td><?php echo htmlspecialchars($book['Subject'] ?? 'General'); ?></td>
                <td><?php echo htmlspecialchars($book['Edition'] ?? 'N/A'); ?></td>
                <td style="text-align: center;">
                    <strong><?php echo $book['TotalCopies'] ?? 0; ?></strong><br>
                    <small style="color: #28a745;">Avail: <?php echo $book['AvailableCopies'] ?? 0; ?></small><br>
                    <small style="color: #dc3545;">Issued: <?php echo $book['IssuedCopies'] ?? 0; ?></small>
                </td>
                <td class="<?php echo $statusClass; ?>" style="text-align: center;">
                    <?php echo $statusText; ?>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    
    <div class="footer">
        <p><strong>WIET Library Management System</strong></p>
        <p>This is an automatically generated report. All data is subject to real-time changes.</p>
        <p>© <?php echo date('Y'); ?> - Walchand Institute of Engineering and Technology</p>
    </div>
    
    <script>
        // Auto-trigger print dialog for PDF generation
        window.onload = function() {
            window.print();
        };
    </script>
</body>
</html>
